const API='http://127.0.0.1:8000',TOKEN_KEY='darkalt-token';
const authView=document.getElementById('auth-view'),libraryView=document.getElementById('library-view'),message=document.getElementById('auth-message');
const IS_STATIC_DEMO=location.hostname.endsWith('github.io');
const token=()=>localStorage.getItem(TOKEN_KEY);
const headers=()=>({'Content-Type':'application/json','Authorization':`Bearer ${token()}`});
async function request(path,options={}){const r=await fetch(API+path,options);const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.detail||'Archive request failed');return data}
function card(x){return `<article class="mini-card"><img src="${x.thumbnail_url||x.image_url}" alt="${x.title}"><div>${x.title}<br>${x.resolution} · ${x.ratio}</div></article>`}
const listToText=items=>(items||[]).join(', ');
async function showLibrary(){try{const [user,favorites,collections,downloads,recent,searches,settings]=await Promise.all([request('/api/auth/me',{headers:headers()}),request('/api/favorites',{headers:headers()}),request('/api/collections',{headers:headers()}),request('/api/downloads',{headers:headers()}),request('/api/recently-viewed',{headers:headers()}),request('/api/search/history',{headers:headers()}),request('/api/settings',{headers:headers()})]);authView.hidden=true;libraryView.hidden=false;document.getElementById('identity').textContent=user.username;document.getElementById('favorite-count').textContent=favorites.total;document.getElementById('favorite-grid').innerHTML=favorites.items.length?favorites.items.map(card).join(''):'<div class="empty-library">NO FAVORITES IN ARCHIVE</div>';document.getElementById('collections').innerHTML=collections.items.length?collections.items.map(x=>`<div class="collection-row"><span>${x.name}</span><small>${x.count} ITEMS</small></div>`).join(''):'<div class="empty-library">NO COLLECTIONS CREATED</div>';document.getElementById('recent').innerHTML=recent.items.length?recent.items.map(x=>`<article class="activity-card"><img src="${x.wallpaper.thumbnail_url||x.wallpaper.image_url}" alt="${x.wallpaper.title}"><div>${x.wallpaper.title}</div></article>`).join(''):'<div class="empty-library">NO RECENT VIEWS</div>';document.getElementById('downloads').innerHTML=downloads.items.length?downloads.items.map(x=>`<div class="download-row"><img src="${x.wallpaper.thumbnail_url||x.wallpaper.image_url}" alt=""><strong>${x.wallpaper.title}</strong><span>${x.variant}</span><span>${new Date(x.downloaded_at).toLocaleString()}</span></div>`).join(''):'<div class="empty-library">NO DOWNLOADS RECORDED</div>';document.getElementById('search-history').innerHTML=searches.items.length?searches.items.map(x=>`<div class="search-row"><strong>${x.query}</strong><span>${x.result_count} RESULTS</span><span>${new Date(x.searched_at).toLocaleString()}</span></div>`).join(''):'<div class="empty-library">NO SEARCHES RECORDED</div>';const form=document.getElementById('settings-form');form.elements.moods.value=listToText(settings.preferred_moods);form.elements.tones.value=listToText(settings.preferred_tones);form.elements.resolutions.value=listToText(settings.preferred_resolutions);form.elements.preset.value=settings.default_download_preset;form.elements.questionable.checked=settings.allow_questionable}catch{localStorage.removeItem(TOKEN_KEY);authView.hidden=false;libraryView.hidden=true}}
async function authenticate(path,form){message.textContent='AUTHENTICATING...';try{const body=Object.fromEntries(new FormData(form));const data=await request(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});localStorage.setItem(TOKEN_KEY,data.access_token);message.textContent='';await showLibrary()}catch(e){message.textContent=e.message}}
document.getElementById('login-form').onsubmit=e=>{e.preventDefault();authenticate('/api/auth/login',e.currentTarget)};
document.getElementById('register-form').onsubmit=e=>{e.preventDefault();authenticate('/api/auth/register',e.currentTarget)};
document.getElementById('collection-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;try{await request('/api/collections',{method:'POST',headers:headers(),body:JSON.stringify({name:new FormData(form).get('name')})});form.reset();await showLibrary()}catch(err){message.textContent=err.message}};
document.getElementById('settings-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,split=name=>form.elements[name].value.split(',').map(x=>x.trim()).filter(Boolean);try{await request('/api/settings',{method:'PUT',headers:headers(),body:JSON.stringify({preferred_moods:split('moods'),preferred_tones:split('tones'),preferred_resolutions:split('resolutions'),default_download_preset:form.elements.preset.value,allow_questionable:form.elements.questionable.checked})});message.textContent='PREFERENCES SAVED'}catch(err){message.textContent=err.message}};
document.getElementById('clear-recent').onclick=async()=>{await request('/api/recently-viewed',{method:'DELETE',headers:headers()});showLibrary()};
document.getElementById('clear-search').onclick=async()=>{await request('/api/search/history',{method:'DELETE',headers:headers()});showLibrary()};
document.getElementById('export-data').onclick=async()=>{const r=await fetch(`${API}/api/data-export`,{headers:headers()});const data=await r.json();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dark-alt-data-export.json';a.click();URL.revokeObjectURL(url)};
document.getElementById('logout').onclick=()=>{localStorage.removeItem(TOKEN_KEY);libraryView.hidden=true;authView.hidden=false};
if(IS_STATIC_DEMO){message.textContent='HOSTED DEMO MODE // ACCOUNT, COLLECTION AND API FEATURES REQUIRE THE LIVE BACKEND.';document.querySelectorAll('#login-form input,#register-form input,#login-form button,#register-form button').forEach(x=>x.disabled=true)}else{if(location.hash==='#register')document.querySelector('#register-form input').focus();if(token())showLibrary()}
