const API='http://127.0.0.1:8000';
const providers=document.getElementById('providers'),jobs=document.getElementById('jobs'),audit=document.getElementById('audit');
const keyInput=document.getElementById('admin-key'),fmt=x=>x?new Date(x).toLocaleString():'—';
const IS_STATIC_DEMO=location.hostname.endsWith('github.io');
const adminKey=()=>sessionStorage.getItem('darkalt-admin-key')||'';
const adminHeaders=()=>({'X-Admin-Key':adminKey()});
function requireKey(){if(adminKey())return true;keyInput.focus();keyInput.placeholder='ADMIN KEY REQUIRED';return false}
async function adminPost(path){if(!requireKey())throw Error('Admin key required');const r=await fetch(API+path,{method:'POST',headers:adminHeaders()});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.detail||'Admin action failed');return data}
async function load(){try{const [h,s,j,a,sem,moods,statsResp]=await Promise.all([fetch(`${API}/api/health`).then(r=>r.json()),fetch(`${API}/api/sources`).then(r=>r.json()),fetch(`${API}/admin/crawler/jobs`).then(r=>r.json()),fetch(`${API}/admin/analysis/status`).then(r=>r.json()),fetch(`${API}/admin/semantic/status`).then(r=>r.json()),fetch(`${API}/api/moods`).then(r=>r.json()),fetch(`${API}/admin/statistics`,{headers:adminHeaders()})]);const stats=statsResp.ok?await statsResp.json():null;document.getElementById('api-status').textContent='ONLINE';document.getElementById('api-status').className='online';document.getElementById('indexed').textContent=String(h.wallpapers).padStart(5,'0');document.getElementById('active').textContent=s.items.filter(x=>x.enabled).length;const dates=s.items.map(x=>x.last_success_at).filter(Boolean).sort();document.getElementById('last-sync').textContent=dates.length?fmt(dates.at(-1)):'NOT SYNCED';providers.innerHTML='<div class="provider-row head"><span>PROVIDER</span><span>STATUS</span><span>DISCOVERED</span><span>ACCEPTED</span><span>DUPLICATES</span><span>ACTION</span></div>'+s.items.map(x=>`<div class="provider-row"><strong>${x.name}</strong><span class="${x.status.toLowerCase()}">${x.status}</span><span>${x.images_discovered}</span><span>${x.images_accepted}</span><span>${x.duplicates}</span><div class="provider-actions">${x.enabled?`<button class="crawl" data-action="crawl" data-key="${x.key}">CRAWL</button><button class="crawl" data-action="disable" data-key="${x.key}">DISABLE</button>`:`<button class="crawl" data-action="enable" data-key="${x.key}">ENABLE</button>`}</div></div>`).join('');jobs.innerHTML='<div class="job-row head"><span>ID</span><span>PROVIDER</span><span>STATUS</span><span>FOUND</span><span>ACCEPT</span><span>DUPES</span><span>REJECT</span><span>FINISHED</span></div>'+j.items.map(x=>`<div class="job-row"><span>${x.id}</span><span>${x.provider}</span><span class="${x.status==='SUCCESS'?'online':'error'}">${x.status}</span><span>${x.discovered}</span><span>${x.accepted}</span><span>${x.duplicates}</span><span>${x.rejected}</span><span>${fmt(x.finished_at)}</span></div>`).join('');if(stats)document.getElementById('telemetry').innerHTML=[['VIEWS',stats.views],['FAVORITES',stats.favorites],['DOWNLOADS',stats.downloads],['SEARCHES',stats.searches],['USERS',stats.users]].map(x=>`<div>${x[0]}<strong>${x[1]}</strong></div>`).join('');document.getElementById('analysis').innerHTML=[['PROCESSED',a.processed],['PENDING',a.pending],['SUCCESS',a.success],['DUPLICATES',a.duplicates],['ERRORS',a.errors]].map(x=>`<div>${x[0]}<strong>${x[1]}</strong></div>`).join('');document.getElementById('semantic').innerHTML=[['PROCESSED',sem.processed],['PENDING',sem.pending],['MOODS',moods.items.length]].map(x=>`<div>${x[0]}<strong>${x[1]}</strong></div>`).join('');await loadAudit()}catch(e){document.getElementById('api-status').textContent='OFFLINE';document.getElementById('api-status').className='error'}}
async function loadAudit(){if(!adminKey()){audit.innerHTML='<div class="empty-admin">ENTER ADMIN KEY TO VIEW AUDIT LOG</div>';return}const r=await fetch(`${API}/admin/audit`,{headers:adminHeaders()});if(!r.ok){audit.innerHTML='<div class="empty-admin">ADMIN KEY REJECTED</div>';return}const data=await r.json();audit.innerHTML=data.items.length?data.items.map(x=>`<div class="audit-row"><span>${x.id}</span><strong>${x.action}</strong><span>${x.target||'—'}</span><span>${JSON.stringify(x.detail)}</span><span>${fmt(x.created_at)}</span></div>`).join(''):'<div class="empty-admin">NO AUDIT EVENTS</div>'}
providers.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;b.disabled=true;b.textContent='WORKING...';try{await adminPost(`/admin/providers/${b.dataset.key}/${action==='crawl'?'crawl?limit=12':action}`);await load()}catch(err){b.disabled=false;b.textContent=action.toUpperCase();keyInput.placeholder=err.message}});
document.getElementById('analyze').onclick=async e=>{const b=e.currentTarget;b.disabled=true;b.textContent='ANALYZING...';try{await adminPost('/admin/analysis/run?limit=30');await load()}finally{b.disabled=false;b.textContent='ANALYZE PENDING'}};
document.getElementById('semantic-run').onclick=async e=>{const b=e.currentTarget;b.disabled=true;b.textContent='CLASSIFYING...';try{await adminPost('/admin/semantic/run?limit=100');await load()}finally{b.disabled=false;b.textContent='CLASSIFY PENDING'}};
document.getElementById('refresh').onclick=load;document.getElementById('save-key').onclick=()=>{sessionStorage.setItem('darkalt-admin-key',keyInput.value);keyInput.value='';load()};keyInput.addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('save-key').click()});if(IS_STATIC_DEMO){document.getElementById('api-status').textContent='STATIC DEMO';document.getElementById('api-status').className='disabled';providers.innerHTML='<div class="empty-admin">ADMIN OPERATIONS REQUIRE THE LIVE BACKEND.</div>';audit.innerHTML='<div class="empty-admin">STATIC DEMO / NO ADMIN API</div>'}else load();
