const IS_STATIC_DEMO=location.hostname.endsWith('github.io');
const API=IS_STATIC_DEMO?'http://127.0.0.1:8000':'http://127.0.0.1:8000';
const PAGE_SIZE=6;
let items=[],visible=[],nextCursor=0,totalCount=0,loading=false,selectedColor=null,sortMode='POPULAR',similarItems=[],defaultDownloadPreset='ORIGINAL';
const urlState=new URLSearchParams(location.search);
const filters={resolution:null,ratio:null,tone:null,mood:urlState.get('mood')||null,category:(urlState.get('category')||'').toUpperCase()||null,q:urlState.get('q')||''};
const grid=document.getElementById('grid'),modal=document.getElementById('modal'),sentinel=document.getElementById('load-sentinel');
const favorites=new Set(JSON.parse(localStorage.getItem('darkalt-favorites')||'[]'));
const authToken=()=>localStorage.getItem('darkalt-token');
const authHeaders=()=>authToken()?{'Authorization':`Bearer ${authToken()}`}:{ };
const unique=x=>[...new Set(x)];
const tagText=x=>unique([...(x.categories||[]),...(x.tags||[]),...(x.moods||[])].map(v=>String(v).toUpperCase())).join(' / ');
const rgb=hex=>hex&&hex.match(/\w\w/g)?.map(x=>parseInt(x,16));
const colorDistance=(a,b)=>{a=rgb(a);b=rgb(b);return(!a||!b)?999:Math.sqrt(a.reduce((sum,x,i)=>sum+(x-b[i])**2,0))};
function currentItems(){let list=selectedColor?items.filter(x=>colorDistance(x.dominant_color,selectedColor)<115):[...items];if(sortMode==='RANDOM')list.sort(()=>Math.random()-.5);else list.sort((a,b)=>b.quality_score-a.quality_score);return list}
function render(){visible=currentItems();grid.innerHTML=visible.length?visible.map((x,i)=>`<article class="card" data-index="${i}"><div class="card-img"><img loading="lazy" src="${x.thumbnail_url||x.image_url}" alt="${x.title} wallpaper"><div class="card-overlay"><button class="preview">PREVIEW</button><button class="download">DOWNLOAD</button></div></div><div class="meta"><div class="meta-top"><span>${x.width} × ${x.height}</span><button class="heart" aria-label="Favorite ${x.title}">${favorites.has(x.id)?'♥':'♡'}</button></div><small>${tagText(x)}</small></div></article>`).join(''):(loading?'':'<div class="empty">NO RESULTS<br><small>THE ARCHIVE CONTAINS NOTHING MATCHING YOUR PARAMETERS.</small></div>');sentinel.textContent=loading?'INDEXING...':nextCursor?'SCROLL TO LOAD MORE':'END OF ARCHIVE'}
function queryParams(){const p=new URLSearchParams({limit:PAGE_SIZE,cursor:nextCursor||0});Object.entries(filters).forEach(([key,value])=>{if(value)p.set(key,value)});return p}
function maybeLoadMore(){const rect=sentinel.getBoundingClientRect();if(nextCursor&&!loading&&rect.top<innerHeight+250)fetchPage()}
async function fetchPage(reset=false){if(IS_STATIC_DEMO){const data=window.DARK_ALT_DEMO||{wallpapers:fallback};items=data.wallpapers.filter(item=>(!filters.category||(item.categories||[]).includes(filters.category))&&(!filters.mood||(item.moods||[]).map(x=>x.toLowerCase()).includes(filters.mood.toLowerCase()))&&(!filters.q||(item.title+' '+tagText(item)+' '+item.source).toLowerCase().includes(filters.q.toLowerCase())));nextCursor=null;totalCount=items.length;document.querySelector('.gallery-head .eyebrow').textContent=`INDEX / ${String(totalCount).padStart(5,'0')}`;render();return}if(loading)return;if(reset){items=[];nextCursor=0;totalCount=0}if(nextCursor===null&&!reset)return;loading=true;render();try{const r=await fetch(`${API}/api/wallpapers?${queryParams()}`,{headers:authHeaders()});if(!r.ok)throw Error();const data=await r.json();const known=new Set(items.map(x=>x.id));items.push(...data.items.filter(x=>!known.has(x.id)));nextCursor=data.next_cursor;totalCount=data.total;document.querySelector('.gallery-head .eyebrow').textContent=`INDEX / ${String(totalCount).padStart(5,'0')}`}catch{if(!items.length)nextCursor=null}finally{loading=false;render();setTimeout(maybeLoadMore,60)}}
async function loadControls(){if(IS_STATIC_DEMO){const demo=window.DARK_ALT_DEMO||{};document.querySelector('.swatches').innerHTML=(demo.colors||[]).slice(0,8).map(x=>`<button data-color="${x.color}" aria-label="Filter by color ${x.color}" title="${x.color} · ${x.count}" style="background:${x.color}"></button>`).join('');document.getElementById('mood-filters').innerHTML=(demo.moods||[]).slice(0,7).map(x=>`<button class="filter ${filters.mood===x.mood?'active':''}" data-group="mood" data-value="${x.mood}">${x.mood.toUpperCase()}</button>`).join('');return}try{const requests=[fetch(`${API}/api/colors`),fetch(`${API}/api/moods`)];if(authToken())requests.push(fetch(`${API}/api/favorites`,{headers:authHeaders()}));const [colors,moods,favs]=await Promise.all(requests);if(colors.ok){const data=await colors.json();document.querySelector('.swatches').innerHTML=data.items.slice(0,8).map(x=>`<button data-color="${x.color}" aria-label="Filter by color ${x.color}" title="${x.color} · ${x.count}" style="background:${x.color}"></button>`).join('')}if(moods.ok){const data=await moods.json();document.getElementById('mood-filters').innerHTML=data.items.slice(0,7).map(x=>`<button class="filter ${filters.mood===x.mood?'active':''}" data-group="mood" data-value="${x.mood}">${x.mood.toUpperCase()}</button>`).join('')}if(favs&&favs.ok){favorites.clear();(await favs.json()).items.forEach(x=>favorites.add(x.id))}if(authToken()){const settingResponse=await fetch(`${API}/api/settings`,{headers:authHeaders()});if(settingResponse.ok){const settings=await settingResponse.json();defaultDownloadPreset=settings.default_download_preset;document.getElementById('download-preset').value=defaultDownloadPreset}}}catch{}}
async function loadDetailExtras(x){const similar=document.getElementById('similar-grid'),collectionSelect=document.getElementById('collection-select');similar.innerHTML='<span class="eyebrow">INDEXING...</span>';collectionSelect.innerHTML='<option value="">ADD TO COLLECTION</option>';if(IS_STATIC_DEMO){similarItems=items.filter(item=>item.id!==x.id&&(item.category===x.category||item.tone===x.tone)).slice(0,6);similar.innerHTML=similarItems.map(item=>`<button class="similar-card" data-id="${item.id}"><img src="${item.thumbnail_url||item.image_url}" alt="${item.title}"><span>${item.title}</span></button>`).join('')||'<span class="eyebrow">NO SIMILAR RECORDS</span>';return}try{const response=await fetch(`${API}/api/similar/${x.id}?limit=6`);const data=await response.json();similarItems=data.items||[];similar.innerHTML=similarItems.map(item=>`<button class="similar-card" data-id="${item.id}"><img src="${item.thumbnail_url||item.image_url}" alt="${item.title}"><span>${item.title}</span></button>`).join('')||'<span class="eyebrow">NO SIMILAR RECORDS</span>';if(authToken()){const collections=await fetch(`${API}/api/collections`,{headers:authHeaders()});if(collections.ok){const data=await collections.json();collectionSelect.innerHTML='<option value="">ADD TO COLLECTION</option>'+data.items.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}}}catch{similar.innerHTML='<span class="eyebrow">SIMILARITY INDEX UNAVAILABLE</span>'}}
function openDetail(x){document.getElementById('modal-img').src=x.image_url;document.getElementById('modal-img').alt=x.title;document.getElementById('modal-title').textContent=x.title;document.getElementById('modal-tags').textContent=tagText(x);document.getElementById('modal-res').textContent=`${x.width} × ${x.height} / ${x.resolution}`;document.getElementById('modal-quality').textContent=Math.round(x.quality_score)+' / 100';document.getElementById('modal-source').textContent=x.source;modal.classList.add('open');modal.setAttribute('aria-hidden','false');modal.dataset.id=x.id;if(!IS_STATIC_DEMO)fetch(`${API}/api/views/${x.id}`,{method:'POST',headers:authHeaders()}).catch(()=>{});loadDetailExtras(x)}
function closeDetail(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
async function toggleFavorite(x){const removing=favorites.has(x.id);removing?favorites.delete(x.id):favorites.add(x.id);localStorage.setItem('darkalt-favorites',JSON.stringify([...favorites]));render();if(authToken()){try{await fetch(`${API}/api/favorites/${x.id}`,{method:removing?'DELETE':'POST',headers:authHeaders()})}catch{}}}
async function downloadWallpaper(x,options={}){const preset=options.preset||'ORIGINAL';if(IS_STATIC_DEMO||preset==='ORIGINAL'){if(!IS_STATIC_DEMO){try{await fetch(`${API}/api/downloads/${x.id}`,{method:'POST',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify({variant:'ORIGINAL'})})}catch{}}window.open(x.image_url,'_blank');return}const params=new URLSearchParams({preset,mode:options.mode||'fit',format:options.format||'JPEG'});if(preset==='CUSTOM'){params.set('width',options.width||1920);params.set('height',options.height||1080)}window.open(`${API}/api/downloads/${x.id}/file?${params}`,'_blank')}
grid.addEventListener('click',async e=>{const card=e.target.closest('.card');if(!card)return;const x=visible[Number(card.dataset.index)];if(e.target.closest('.heart'))return toggleFavorite(x);if(e.target.closest('.download'))return downloadWallpaper(x);openDetail(x)});
document.querySelector('.modal-close').onclick=closeDetail;document.querySelector('.modal-backdrop').onclick=closeDetail;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail()});
document.getElementById('download-preset').onchange=e=>document.getElementById('custom-size').hidden=e.target.value!=='CUSTOM';
document.getElementById('modal-download').onclick=()=>downloadWallpaper(items.find(x=>x.id===modal.dataset.id),{preset:document.getElementById('download-preset').value,mode:document.getElementById('download-mode').value,format:document.getElementById('download-format').value,width:document.getElementById('custom-width').value,height:document.getElementById('custom-height').value});
document.getElementById('modal-favorite').onclick=async()=>{await toggleFavorite(items.find(x=>x.id===modal.dataset.id));closeDetail()};
document.getElementById('similar-grid').onclick=e=>{const card=e.target.closest('[data-id]');if(!card)return;const item=similarItems.find(x=>x.id===card.dataset.id);if(item)openDetail(item)};
document.getElementById('modal-collection').onclick=async()=>{const wallpaper=items.find(x=>x.id===modal.dataset.id)||similarItems.find(x=>x.id===modal.dataset.id);const collectionId=document.getElementById('collection-select').value;if(!authToken()){location.href='account.html';return}if(!collectionId||!wallpaper)return;const button=document.getElementById('modal-collection');button.disabled=true;try{const response=await fetch(`${API}/api/collections/${collectionId}/items/${wallpaper.id}`,{method:'POST',headers:authHeaders()});if(!response.ok)throw Error();button.textContent='SAVED';setTimeout(()=>button.textContent='ADD +',1200)}catch{button.textContent='ERROR'}finally{button.disabled=false}};
document.querySelector('.filters').addEventListener('click',e=>{const button=e.target.closest('.filter');if(!button)return;const group=button.dataset.group,value=button.dataset.value;const wasActive=button.classList.contains('active');document.querySelectorAll(`.filter[data-group="${group}"]`).forEach(x=>x.classList.remove('active'));filters[group]=wasActive?null:value;if(!wasActive)button.classList.add('active');fetchPage(true)});
document.querySelectorAll('.tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');sortMode=btn.textContent==='RANDOM'?'RANDOM':'POPULAR';render()}));
let searchTimer;document.getElementById('search').addEventListener('input',e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{filters.q=e.target.value.trim();fetchPage(true)},250)});
document.querySelector('.swatches').addEventListener('click',e=>{const swatch=e.target.closest('[data-color]');if(!swatch)return;document.querySelectorAll('.swatches [data-color]').forEach(x=>x.classList.remove('active'));if(selectedColor===swatch.dataset.color){selectedColor=null}else{selectedColor=swatch.dataset.color;swatch.classList.add('active')}render()});
new IntersectionObserver(entries=>{if(entries[0].isIntersecting)maybeLoadMore()},{rootMargin:'350px'}).observe(sentinel);
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('search').focus()}});
(async()=>{document.getElementById('search').value=filters.q;await loadControls();await fetchPage(true)})();
