"""user preferences

Revision ID: 4d1074ebbbfd
Revises: a5746c4e20ef
Create Date: 2026-09-14 16:06:32.263587
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4d1074ebbbfd'
down_revision: Union[str, None] = 'a5746c4e20ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_moods', sa.JSON(), nullable=False),
    sa.Column('preferred_tones', sa.JSON(), nullable=False),
    sa.Column('preferred_resolutions', sa.JSON(), nullable=False),
    sa.Column('default_download_preset', sa.String(length=20), nullable=False),
    sa.Column('allow_questionable', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
