"""initial schema

Revision ID: a5746c4e20ef
Revises: 
Create Date: 2026-09-14 15:39:33.520593
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a5746c4e20ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('provider_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('images_discovered', sa.Integer(), nullable=False),
    sa.Column('images_accepted', sa.Integer(), nullable=False),
    sa.Column('images_rejected', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_states_key'), 'provider_states', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('wallpapers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('license', sa.String(length=180), nullable=True),
    sa.Column('license_url', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('ratio', sa.String(length=20), nullable=False),
    sa.Column('orientation', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('dominant_color', sa.String(length=10), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('nsfw_score', sa.Float(), nullable=False),
    sa.Column('is_ai', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('provider_key', sa.String(length=80), nullable=False),
    sa.Column('provider_external_id', sa.String(length=200), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash'),
    sa.UniqueConstraint('provider_key', 'provider_external_id', name='uq_provider_external')
    )
    op.create_index(op.f('ix_wallpapers_orientation'), 'wallpapers', ['orientation'], unique=False)
    op.create_index(op.f('ix_wallpapers_provider_key'), 'wallpapers', ['provider_key'], unique=False)
    op.create_index(op.f('ix_wallpapers_ratio'), 'wallpapers', ['ratio'], unique=False)
    op.create_index(op.f('ix_wallpapers_resolution'), 'wallpapers', ['resolution'], unique=False)
    op.create_index(op.f('ix_wallpapers_slug'), 'wallpapers', ['slug'], unique=True)
    op.create_index(op.f('ix_wallpapers_source'), 'wallpapers', ['source'], unique=False)
    op.create_index(op.f('ix_wallpapers_tone'), 'wallpapers', ['tone'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_collection_name')
    )
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wallpaper_id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=30), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallpaper_id'], ['wallpapers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloads_user_id'), 'downloads', ['user_id'], unique=False)
    op.create_index(op.f('ix_downloads_wallpaper_id'), 'downloads', ['wallpaper_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallpaper_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallpaper_id'], ['wallpapers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'wallpaper_id', name='uq_user_favorite')
    )
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorites_wallpaper_id'), 'favorites', ['wallpaper_id'], unique=False)
    op.create_table('image_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallpaper_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('phash', sa.String(length=32), nullable=True),
    sa.Column('dhash', sa.String(length=32), nullable=True),
    sa.Column('ahash', sa.String(length=32), nullable=True),
    sa.Column('dominant_color', sa.String(length=10), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('saturation', sa.Float(), nullable=True),
    sa.Column('sharpness', sa.Float(), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['wallpapers.id'], ),
    sa.ForeignKeyConstraint(['wallpaper_id'], ['wallpapers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_analyses_brightness'), 'image_analyses', ['brightness'], unique=False)
    op.create_index(op.f('ix_image_analyses_dominant_color'), 'image_analyses', ['dominant_color'], unique=False)
    op.create_index(op.f('ix_image_analyses_phash'), 'image_analyses', ['phash'], unique=False)
    op.create_index(op.f('ix_image_analyses_sha256'), 'image_analyses', ['sha256'], unique=False)
    op.create_index(op.f('ix_image_analyses_status'), 'image_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_image_analyses_wallpaper_id'), 'image_analyses', ['wallpaper_id'], unique=True)
    op.create_table('search_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(length=300), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('searched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_events_query'), 'search_events', ['query'], unique=False)
    op.create_index(op.f('ix_search_events_searched_at'), 'search_events', ['searched_at'], unique=False)
    op.create_index(op.f('ix_search_events_user_id'), 'search_events', ['user_id'], unique=False)
    op.create_table('semantic_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallpaper_id', sa.Integer(), nullable=False),
    sa.Column('moods', sa.JSON(), nullable=False),
    sa.Column('generated_tags', sa.JSON(), nullable=False),
    sa.Column('scene', sa.String(length=80), nullable=True),
    sa.Column('style', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wallpaper_id'], ['wallpapers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_profiles_scene'), 'semantic_profiles', ['scene'], unique=False)
    op.create_index(op.f('ix_semantic_profiles_style'), 'semantic_profiles', ['style'], unique=False)
    op.create_index(op.f('ix_semantic_profiles_wallpaper_id'), 'semantic_profiles', ['wallpaper_id'], unique=True)
    op.create_table('view_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wallpaper_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wallpaper_id'], ['wallpapers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_view_events_user_id'), 'view_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_view_events_viewed_at'), 'view_events', ['viewed_at'], unique=False)
    op.create_index(op.f('ix_view_events_wallpaper_id'), 'view_events', ['wallpaper_id'], unique=False)
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('wallpaper_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['wallpaper_id'], ['wallpapers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'wallpaper_id', name='uq_collection_wallpaper')
    )
    op.create_index(op.f('ix_collection_items_collection_id'), 'collection_items', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_items_wallpaper_id'), 'collection_items', ['wallpaper_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_items_wallpaper_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_collection_id'), table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_view_events_wallpaper_id'), table_name='view_events')
    op.drop_index(op.f('ix_view_events_viewed_at'), table_name='view_events')
    op.drop_index(op.f('ix_view_events_user_id'), table_name='view_events')
    op.drop_table('view_events')
    op.drop_index(op.f('ix_semantic_profiles_wallpaper_id'), table_name='semantic_profiles')
    op.drop_index(op.f('ix_semantic_profiles_style'), table_name='semantic_profiles')
    op.drop_index(op.f('ix_semantic_profiles_scene'), table_name='semantic_profiles')
    op.drop_table('semantic_profiles')
    op.drop_index(op.f('ix_search_events_user_id'), table_name='search_events')
    op.drop_index(op.f('ix_search_events_searched_at'), table_name='search_events')
    op.drop_index(op.f('ix_search_events_query'), table_name='search_events')
    op.drop_table('search_events')
    op.drop_index(op.f('ix_image_analyses_wallpaper_id'), table_name='image_analyses')
    op.drop_index(op.f('ix_image_analyses_status'), table_name='image_analyses')
    op.drop_index(op.f('ix_image_analyses_sha256'), table_name='image_analyses')
    op.drop_index(op.f('ix_image_analyses_phash'), table_name='image_analyses')
    op.drop_index(op.f('ix_image_analyses_dominant_color'), table_name='image_analyses')
    op.drop_index(op.f('ix_image_analyses_brightness'), table_name='image_analyses')
    op.drop_table('image_analyses')
    op.drop_index(op.f('ix_favorites_wallpaper_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_downloads_wallpaper_id'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_user_id'), table_name='downloads')
    op.drop_table('downloads')
    op.drop_index(op.f('ix_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_wallpapers_tone'), table_name='wallpapers')
    op.drop_index(op.f('ix_wallpapers_source'), table_name='wallpapers')
    op.drop_index(op.f('ix_wallpapers_slug'), table_name='wallpapers')
    op.drop_index(op.f('ix_wallpapers_resolution'), table_name='wallpapers')
    op.drop_index(op.f('ix_wallpapers_ratio'), table_name='wallpapers')
    op.drop_index(op.f('ix_wallpapers_provider_key'), table_name='wallpapers')
    op.drop_index(op.f('ix_wallpapers_orientation'), table_name='wallpapers')
    op.drop_table('wallpapers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_provider_states_key'), table_name='provider_states')
    op.drop_table('provider_states')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
